typography_spectrum: 0.50297
color:
  brandColors:
    - '#ffffff'
    - '#636363'
    - '#c3c3c3'
    - '#9a0000'
    - '#b94b4d'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.448
analytics:
  google: UA-69175424-2
  facebook: null
  twitter: null
name: auger-dominguez
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Christopher Auger-Domínguez Photography
description: 'Photographer, Geographer, Drone Pilot'
purpose: []
