name: auger-dominguez
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7570461758878082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#636363'
    - '#c3c3c3'
    - '#9a0000'
    - '#b94b4d'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
